import assert from "node:assert/strict";
import { chmod, cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { canonicalJson } from "../../src/contracts/index.ts";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const executable = path.join(repositoryRoot, "bin", "cardnews");
const synthetic = path.join(repositoryRoot, "fixtures", "synthetic");
const originNote = "Deterministically generated by fixtures/synthetic/generate.mjs (seed-orbit)";

const runJson = async (cwd, args, expectedCode = 0) => {
  const result = await new Promise((resolve, reject) => {
    const child = spawn(executable, [...args, "--json"], {
      cwd,
      env: process.env,
      stdio: ["ignore", "pipe", "pipe"]
    });
    const stdout = [];
    const stderr = [];
    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.stderr.on("data", (chunk) => stderr.push(chunk));
    child.once("error", reject);
    child.once("close", (code) => resolve({
      code,
      stdout: Buffer.concat(stdout).toString("utf8"),
      stderr: Buffer.concat(stderr).toString("utf8")
    }));
  });
  assert.equal(result.code, expectedCode, `${args.join(" ")}\n${result.stdout}\n${result.stderr}`);
  assert.equal(result.stderr, "");
  return JSON.parse(result.stdout);
};

const authorAndCommit = async (
  workspace,
  job,
  stage,
  fixtureName,
  dependencyField,
  dependencyDigest
) => {
  const scaffold = await runJson(workspace, ["scaffold-record", "--job", job, "--stage", stage]);
  const value = JSON.parse(await readFile(path.join(synthetic, "records", fixtureName), "utf8"));
  value[dependencyField] = dependencyDigest;
  await writeFile(
    path.join(workspace, scaffold.result.draftPath),
    `${canonicalJson(value)}\n`
  );
  const committed = await runJson(workspace, [
    "commit-record", "--job", job, "--stage", stage, "--input", scaffold.result.draftPath
  ]);
  return committed.result.contractDigest;
};

const prepareJob = async (context, slug) => {
  const workspace = await mkdtemp(path.join(os.tmpdir(), `cardnews-cli-${slug}-`));
  context.after(() => rm(workspace, { recursive: true, force: true }));
  const source = path.join(workspace, "article.html");
  const asset = path.join(workspace, "seed-orbit.bin");
  await cp(path.join(synthetic, "source", "article.html"), source);
  await cp(path.join(synthetic, "assets", "seed-orbit", "asset.bin"), asset);
  const initialized = await runJson(workspace, [
    "init", "--slug", slug, "--target", "portrait-social-1080x1350", "--cards", "7"
  ]);
  const job = initialized.result.jobPath;
  const ingested = await runJson(workspace, [
    "ingest", "--job", job, "--file", source, "--allowed-root", workspace
  ]);
  const editorial = await authorAndCommit(
    workspace,
    job,
    "editorial-brief",
    "editorial-brief.json",
    "sourceEnvelopeDigest",
    ingested.result.contractDigest
  );
  const storyboard = await authorAndCommit(
    workspace,
    job,
    "storyboard",
    "storyboard.json",
    "editorialBriefDigest",
    editorial
  );
  const recipe = await authorAndCommit(
    workspace,
    job,
    "visual-recipe",
    "visual-recipe.json",
    "storyboardDigest",
    storyboard
  );
  await authorAndCommit(
    workspace,
    job,
    "render-spec",
    "render-spec.json",
    "visualRecipeDigest",
    recipe
  );
  const imported = await runJson(workspace, [
    "import-asset", "--job", job, "--file", asset, "--allowed-root", workspace,
    "--rights", "generated", "--origin-note", originNote, "--slot", "hero"
  ]);
  const scaffold = await runJson(workspace, [
    "scaffold-record", "--job", job, "--stage", "editorial-brief"
  ]);
  const revised = JSON.parse(
    await readFile(path.join(synthetic, "records", "editorial-brief.json"), "utf8")
  );
  revised.sourceEnvelopeDigest = ingested.result.contractDigest;
  revised.thesis = `${revised.thesis} Revised.`;
  await writeFile(
    path.join(workspace, scaffold.result.draftPath),
    `${canonicalJson(revised)}\n`
  );
  return {
    workspace,
    job,
    artifactPath: path.join(workspace, imported.result.artifactPath),
    metadataPath: path.join(workspace, imported.result.metadataPath),
    revisionArgs: [
      "commit-record", "--job", job, "--stage", "editorial-brief",
      "--input", scaffold.result.draftPath, "--force"
    ]
  };
};

const assertProjectionAndRevisionReject = async (prepared) => {
  const projection = await runJson(prepared.workspace, ["render", "--job", prepared.job], 3);
  const revision = await runJson(prepared.workspace, prepared.revisionArgs, 3);
  assert.equal(projection.error.code, "ASSET_INTEGRITY_INVALID");
  assert.equal(revision.error.code, "ASSET_INTEGRITY_INVALID");
};

test("Given accepted asset bytes are replaced, When projection and revision read them, Then both fail closed", async (context) => {
  const prepared = await prepareJob(context, "asset-byte-integrity");
  const original = await readFile(prepared.artifactPath);
  const tampered = Buffer.from(original).fill(0, 0, 1);
  await chmod(prepared.artifactPath, 0o600);
  await writeFile(prepared.artifactPath, tampered);

  await assertProjectionAndRevisionReject(prepared);

  assert.deepEqual(await readFile(prepared.artifactPath), tampered);
});

test("Given accepted origin provenance is replaced with a nonblank forgery, When projection and revision read it, Then both fail closed", async (context) => {
  const prepared = await prepareJob(context, "asset-provenance-integrity");
  const metadata = JSON.parse(await readFile(prepared.metadataPath, "utf8"));
  metadata.originNote = "Forged nonblank provenance";
  await chmod(prepared.metadataPath, 0o600);
  await writeFile(prepared.metadataPath, canonicalJson(metadata));

  await assertProjectionAndRevisionReject(prepared);

  assert.equal(
    JSON.parse(await readFile(prepared.metadataPath, "utf8")).originNote,
    "Forged nonblank provenance"
  );
});

test("Given accepted origin provenance becomes whitespace, When projection and revision read it, Then both fail closed", async (context) => {
  const prepared = await prepareJob(context, "asset-blank-provenance");
  const metadata = JSON.parse(await readFile(prepared.metadataPath, "utf8"));
  metadata.originNote = "   ";
  await chmod(prepared.metadataPath, 0o600);
  await writeFile(prepared.metadataPath, canonicalJson(metadata));

  await assertProjectionAndRevisionReject(prepared);

  assert.equal(JSON.parse(await readFile(prepared.metadataPath, "utf8")).originNote, "   ");
});
